spring.application.name=act4_t4
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/actividad4?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=cocodriloS1
spring.jpa.hibernate.ddl-auto=update